/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface SearchResult {
    type: string;
    description: string;
    displaySymbol: string;
    symbol: string;
}
export interface CompanyProfileResult {
    marketCap: number;
    logo: string;
    name: string;
    currency: string;
    exchange: string;
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export type Time = bigint;
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface QuoteResult {
    change: number;
    price: number;
    changePercent: number;
}
export interface Alert {
    id: bigint;
    active: boolean;
    expiresAt: Time;
    createdAt: Time;
    seen: boolean;
    targetPrice: number;
    triggered: boolean;
    symbol: string;
    condition: AlertCondition;
}
export interface WatchlistEntry {
    company: string;
    addedAt: Time;
    symbol: string;
}
export interface NewsItem {
    url: string;
    source: string;
    headline: string;
    summary: string;
    category: string;
    image: string;
}
export interface UserProfile {
    country: string;
    riskTolerance: string;
    createdAt: Time;
    preferredIndustry: string;
    investmentGoals: string;
    hasCompletedOnboarding: boolean;
}
export interface http_header {
    value: string;
    name: string;
}
export enum AlertCondition {
    Below = "Below",
    Above = "Above"
}
export interface backendInterface {
    addToWatchlist(symbol: string, company: string): Promise<void>;
    createAlert(symbol: string, targetPrice: number, condition: AlertCondition): Promise<Alert>;
    deleteAlert(alertId: bigint): Promise<void>;
    finnhubTransform(args: TransformationInput): Promise<TransformationOutput>;
    getCompanyNews(symbol: string, fromDate: string, toDate: string): Promise<Array<NewsItem>>;
    getCompanyProfile(symbol: string): Promise<CompanyProfileResult>;
    getMyAlerts(): Promise<Array<Alert>>;
    getMyProfile(): Promise<UserProfile | null>;
    getMyTriggeredAlerts(): Promise<Array<Alert>>;
    getMyWatchlist(): Promise<Array<WatchlistEntry>>;
    getQuote(symbol: string): Promise<QuoteResult>;
    hasCompletedOnboarding(): Promise<boolean>;
    isInWatchlist(symbol: string): Promise<boolean>;
    markAlertSeen(alertId: bigint): Promise<void>;
    removeFromWatchlist(symbol: string): Promise<void>;
    saveProfile(profile: UserProfile): Promise<void>;
    searchStocks(searchQuery: string): Promise<Array<SearchResult>>;
    setFinnhubKey(key: string): Promise<void>;
    toggleAlert(alertId: bigint, active: boolean): Promise<void>;
}
import type { Alert as _Alert, AlertCondition as _AlertCondition, Time as _Time, UserProfile as _UserProfile } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addToWatchlist(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addToWatchlist(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addToWatchlist(arg0, arg1);
            return result;
        }
    }
    async createAlert(arg0: string, arg1: number, arg2: AlertCondition): Promise<Alert> {
        if (this.processError) {
            try {
                const result = await this.actor.createAlert(arg0, arg1, to_candid_AlertCondition_n1(this._uploadFile, this._downloadFile, arg2));
                return from_candid_Alert_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createAlert(arg0, arg1, to_candid_AlertCondition_n1(this._uploadFile, this._downloadFile, arg2));
            return from_candid_Alert_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteAlert(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAlert(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAlert(arg0);
            return result;
        }
    }
    async finnhubTransform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.finnhubTransform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.finnhubTransform(arg0);
            return result;
        }
    }
    async getCompanyNews(arg0: string, arg1: string, arg2: string): Promise<Array<NewsItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCompanyNews(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCompanyNews(arg0, arg1, arg2);
            return result;
        }
    }
    async getCompanyProfile(arg0: string): Promise<CompanyProfileResult> {
        if (this.processError) {
            try {
                const result = await this.actor.getCompanyProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCompanyProfile(arg0);
            return result;
        }
    }
    async getMyAlerts(): Promise<Array<Alert>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyAlerts();
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyAlerts();
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyProfile();
                return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyProfile();
            return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyTriggeredAlerts(): Promise<Array<Alert>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyTriggeredAlerts();
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyTriggeredAlerts();
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyWatchlist(): Promise<Array<WatchlistEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyWatchlist();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyWatchlist();
            return result;
        }
    }
    async getQuote(arg0: string): Promise<QuoteResult> {
        if (this.processError) {
            try {
                const result = await this.actor.getQuote(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQuote(arg0);
            return result;
        }
    }
    async hasCompletedOnboarding(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.hasCompletedOnboarding();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.hasCompletedOnboarding();
            return result;
        }
    }
    async isInWatchlist(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isInWatchlist(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isInWatchlist(arg0);
            return result;
        }
    }
    async markAlertSeen(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markAlertSeen(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markAlertSeen(arg0);
            return result;
        }
    }
    async removeFromWatchlist(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeFromWatchlist(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeFromWatchlist(arg0);
            return result;
        }
    }
    async saveProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveProfile(arg0);
            return result;
        }
    }
    async searchStocks(arg0: string): Promise<Array<SearchResult>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchStocks(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchStocks(arg0);
            return result;
        }
    }
    async setFinnhubKey(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setFinnhubKey(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setFinnhubKey(arg0);
            return result;
        }
    }
    async toggleAlert(arg0: bigint, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleAlert(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleAlert(arg0, arg1);
            return result;
        }
    }
}
function from_candid_AlertCondition_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AlertCondition): AlertCondition {
    return from_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function from_candid_Alert_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Alert): Alert {
    return from_candid_record_n4(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    active: boolean;
    expiresAt: _Time;
    createdAt: _Time;
    seen: boolean;
    targetPrice: number;
    triggered: boolean;
    symbol: string;
    condition: _AlertCondition;
}): {
    id: bigint;
    active: boolean;
    expiresAt: Time;
    createdAt: Time;
    seen: boolean;
    targetPrice: number;
    triggered: boolean;
    symbol: string;
    condition: AlertCondition;
} {
    return {
        id: value.id,
        active: value.active,
        expiresAt: value.expiresAt,
        createdAt: value.createdAt,
        seen: value.seen,
        targetPrice: value.targetPrice,
        triggered: value.triggered,
        symbol: value.symbol,
        condition: from_candid_AlertCondition_n5(_uploadFile, _downloadFile, value.condition)
    };
}
function from_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Below: null;
} | {
    Above: null;
}): AlertCondition {
    return "Below" in value ? AlertCondition.Below : "Above" in value ? AlertCondition.Above : value;
}
function from_candid_vec_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Alert>): Array<Alert> {
    return value.map((x)=>from_candid_Alert_n3(_uploadFile, _downloadFile, x));
}
function to_candid_AlertCondition_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AlertCondition): _AlertCondition {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AlertCondition): {
    Below: null;
} | {
    Above: null;
} {
    return value == AlertCondition.Below ? {
        Below: null
    } : value == AlertCondition.Above ? {
        Above: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
