/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const AlertCondition = IDL.Variant({
  'Below' : IDL.Null,
  'Above' : IDL.Null,
});
export const Time = IDL.Int;
export const Alert = IDL.Record({
  'id' : IDL.Nat,
  'active' : IDL.Bool,
  'expiresAt' : Time,
  'createdAt' : Time,
  'seen' : IDL.Bool,
  'targetPrice' : IDL.Float64,
  'triggered' : IDL.Bool,
  'symbol' : IDL.Text,
  'condition' : AlertCondition,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const NewsItem = IDL.Record({
  'url' : IDL.Text,
  'source' : IDL.Text,
  'headline' : IDL.Text,
  'summary' : IDL.Text,
  'category' : IDL.Text,
  'image' : IDL.Text,
});
export const CompanyProfileResult = IDL.Record({
  'marketCap' : IDL.Float64,
  'logo' : IDL.Text,
  'name' : IDL.Text,
  'currency' : IDL.Text,
  'exchange' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'country' : IDL.Text,
  'riskTolerance' : IDL.Text,
  'createdAt' : Time,
  'preferredIndustry' : IDL.Text,
  'investmentGoals' : IDL.Text,
  'hasCompletedOnboarding' : IDL.Bool,
});
export const WatchlistEntry = IDL.Record({
  'company' : IDL.Text,
  'addedAt' : Time,
  'symbol' : IDL.Text,
});
export const QuoteResult = IDL.Record({
  'change' : IDL.Float64,
  'price' : IDL.Float64,
  'changePercent' : IDL.Float64,
});
export const SearchResult = IDL.Record({
  'type' : IDL.Text,
  'description' : IDL.Text,
  'displaySymbol' : IDL.Text,
  'symbol' : IDL.Text,
});

export const idlService = IDL.Service({
  'addToWatchlist' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'createAlert' : IDL.Func(
      [IDL.Text, IDL.Float64, AlertCondition],
      [Alert],
      [],
    ),
  'deleteAlert' : IDL.Func([IDL.Nat], [], []),
  'finnhubTransform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'getCompanyNews' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Vec(NewsItem)],
      [],
    ),
  'getCompanyProfile' : IDL.Func([IDL.Text], [CompanyProfileResult], []),
  'getMyAlerts' : IDL.Func([], [IDL.Vec(Alert)], ['query']),
  'getMyProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getMyTriggeredAlerts' : IDL.Func([], [IDL.Vec(Alert)], ['query']),
  'getMyWatchlist' : IDL.Func([], [IDL.Vec(WatchlistEntry)], ['query']),
  'getQuote' : IDL.Func([IDL.Text], [QuoteResult], []),
  'hasCompletedOnboarding' : IDL.Func([], [IDL.Bool], ['query']),
  'isInWatchlist' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'markAlertSeen' : IDL.Func([IDL.Nat], [], []),
  'removeFromWatchlist' : IDL.Func([IDL.Text], [], []),
  'saveProfile' : IDL.Func([UserProfile], [], []),
  'searchStocks' : IDL.Func([IDL.Text], [IDL.Vec(SearchResult)], []),
  'setFinnhubKey' : IDL.Func([IDL.Text], [], []),
  'toggleAlert' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const AlertCondition = IDL.Variant({
    'Below' : IDL.Null,
    'Above' : IDL.Null,
  });
  const Time = IDL.Int;
  const Alert = IDL.Record({
    'id' : IDL.Nat,
    'active' : IDL.Bool,
    'expiresAt' : Time,
    'createdAt' : Time,
    'seen' : IDL.Bool,
    'targetPrice' : IDL.Float64,
    'triggered' : IDL.Bool,
    'symbol' : IDL.Text,
    'condition' : AlertCondition,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const NewsItem = IDL.Record({
    'url' : IDL.Text,
    'source' : IDL.Text,
    'headline' : IDL.Text,
    'summary' : IDL.Text,
    'category' : IDL.Text,
    'image' : IDL.Text,
  });
  const CompanyProfileResult = IDL.Record({
    'marketCap' : IDL.Float64,
    'logo' : IDL.Text,
    'name' : IDL.Text,
    'currency' : IDL.Text,
    'exchange' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'country' : IDL.Text,
    'riskTolerance' : IDL.Text,
    'createdAt' : Time,
    'preferredIndustry' : IDL.Text,
    'investmentGoals' : IDL.Text,
    'hasCompletedOnboarding' : IDL.Bool,
  });
  const WatchlistEntry = IDL.Record({
    'company' : IDL.Text,
    'addedAt' : Time,
    'symbol' : IDL.Text,
  });
  const QuoteResult = IDL.Record({
    'change' : IDL.Float64,
    'price' : IDL.Float64,
    'changePercent' : IDL.Float64,
  });
  const SearchResult = IDL.Record({
    'type' : IDL.Text,
    'description' : IDL.Text,
    'displaySymbol' : IDL.Text,
    'symbol' : IDL.Text,
  });
  
  return IDL.Service({
    'addToWatchlist' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'createAlert' : IDL.Func(
        [IDL.Text, IDL.Float64, AlertCondition],
        [Alert],
        [],
      ),
    'deleteAlert' : IDL.Func([IDL.Nat], [], []),
    'finnhubTransform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'getCompanyNews' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Vec(NewsItem)],
        [],
      ),
    'getCompanyProfile' : IDL.Func([IDL.Text], [CompanyProfileResult], []),
    'getMyAlerts' : IDL.Func([], [IDL.Vec(Alert)], ['query']),
    'getMyProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getMyTriggeredAlerts' : IDL.Func([], [IDL.Vec(Alert)], ['query']),
    'getMyWatchlist' : IDL.Func([], [IDL.Vec(WatchlistEntry)], ['query']),
    'getQuote' : IDL.Func([IDL.Text], [QuoteResult], []),
    'hasCompletedOnboarding' : IDL.Func([], [IDL.Bool], ['query']),
    'isInWatchlist' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'markAlertSeen' : IDL.Func([IDL.Nat], [], []),
    'removeFromWatchlist' : IDL.Func([IDL.Text], [], []),
    'saveProfile' : IDL.Func([UserProfile], [], []),
    'searchStocks' : IDL.Func([IDL.Text], [IDL.Vec(SearchResult)], []),
    'setFinnhubKey' : IDL.Func([IDL.Text], [], []),
    'toggleAlert' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
  });
};

export const init = ({ IDL }) => { return []; };