/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Alert {
  'id' : bigint,
  'active' : boolean,
  'expiresAt' : Time,
  'createdAt' : Time,
  'seen' : boolean,
  'targetPrice' : number,
  'triggered' : boolean,
  'symbol' : string,
  'condition' : AlertCondition,
}
export type AlertCondition = { 'Below' : null } |
  { 'Above' : null };
export interface CompanyProfileResult {
  'marketCap' : number,
  'logo' : string,
  'name' : string,
  'currency' : string,
  'exchange' : string,
}
export interface NewsItem {
  'url' : string,
  'source' : string,
  'headline' : string,
  'summary' : string,
  'category' : string,
  'image' : string,
}
export interface QuoteResult {
  'change' : number,
  'price' : number,
  'changePercent' : number,
}
export interface SearchResult {
  'type' : string,
  'description' : string,
  'displaySymbol' : string,
  'symbol' : string,
}
export type Time = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile {
  'country' : string,
  'riskTolerance' : string,
  'createdAt' : Time,
  'preferredIndustry' : string,
  'investmentGoals' : string,
  'hasCompletedOnboarding' : boolean,
}
export interface WatchlistEntry {
  'company' : string,
  'addedAt' : Time,
  'symbol' : string,
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  'addToWatchlist' : ActorMethod<[string, string], undefined>,
  'createAlert' : ActorMethod<[string, number, AlertCondition], Alert>,
  'deleteAlert' : ActorMethod<[bigint], undefined>,
  'finnhubTransform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'getCompanyNews' : ActorMethod<[string, string, string], Array<NewsItem>>,
  'getCompanyProfile' : ActorMethod<[string], CompanyProfileResult>,
  'getMyAlerts' : ActorMethod<[], Array<Alert>>,
  'getMyProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getMyTriggeredAlerts' : ActorMethod<[], Array<Alert>>,
  'getMyWatchlist' : ActorMethod<[], Array<WatchlistEntry>>,
  'getQuote' : ActorMethod<[string], QuoteResult>,
  'hasCompletedOnboarding' : ActorMethod<[], boolean>,
  'isInWatchlist' : ActorMethod<[string], boolean>,
  'markAlertSeen' : ActorMethod<[bigint], undefined>,
  'removeFromWatchlist' : ActorMethod<[string], undefined>,
  'saveProfile' : ActorMethod<[UserProfile], undefined>,
  'searchStocks' : ActorMethod<[string], Array<SearchResult>>,
  'setFinnhubKey' : ActorMethod<[string], undefined>,
  'toggleAlert' : ActorMethod<[bigint, boolean], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];